[env]
; framework = arduino
; monitor_speed = 115200
; upload_speed = 921600
; platform = platformio/espressif32
; platform_packages = platformio/framework-arduinoespressif32
; lib_deps = 
;     janelia-arduino/TMC2209
;     pkerspe/ESP-FlexyStepper

[env:esp32_pico_main]
framework               =  arduino
board                   =  pico32
board_build.flash_mode  =  qio
platform                =  platformio/espressif32@6.13.0
; platform_packages       =  platformio/framework-arduinoespressif32@3.20017.241212+sha.dcc1105b ;; 3.20014.231204 ;; 3.20017.0 ;; ~3.20009.0 ;; 3.20014.231204
platform_packages       =  platformio/framework-arduinoespressif32 @ https://github.com/troyhacks/troymota_fast.git ;; https://github.com/troyhacks/arduino-esp32.git#release/v2.x @ 2.0.17+sha.381be90
                           toolchain-xtensa-esp32s3@~12.2
upload_speed            =  921600
; build_unflags           =  -Os
build_flags             =  -O2
                           -D CORE_DEBUG_LEVEL=5
lib_deps =                 janelia-arduino/TMC2209
                           pkerspe/ESP-FlexyStepper#v1.5.1
build_src_filter        =  +<main.cpp>
monitor_filters         =  esp32_exception_decoder
                           colorize
board_build.f_flash     =  80000000L
monitor_speed           =  115200


[env:seeed_xiao_esp32c3_remote]
board = seeed_xiao_esp32c3
framework = arduino
platform                =  platformio/espressif32@6.13.0
platform_packages       =  platformio/framework-arduinoespressif32 @ https://github.com/troyhacks/troymota_fast.git ;; https://github.com/troyhacks/arduino-esp32.git#release/v2.x @ 2.0.17+sha.381be90
                           toolchain-xtensa-esp32s3@~12.2
monitor_speed = 115200
lib_deps =
    adafruit/Adafruit SSD1306 @ ^2.5.9
    adafruit/Adafruit GFX Library @ ^1.11.9
build_src_filter =
    +<remote.cpp>


[env:waveshare_s3_main]
board                   =  esp32-s3-devkitc-1
framework               =  arduino
platform                =  platformio/espressif32@6.13.0
platform_packages       =  platformio/framework-arduinoespressif32 @ https://github.com/troyhacks/troymota_fast.git ;; https://github.com/troyhacks/arduino-esp32.git#release/v2.x @ 2.0.17+sha.381be90
                          ;  toolchain-xtensa-esp32s3@~12.2
upload_speed            =  921600
monitor_speed           =  115200
build_flags             =  -O2
                           -D CORE_DEBUG_LEVEL=5
                           -D ARDUINO_USB_MODE=1
                           -D ARDUINO_USB_CDC_ON_BOOT=1
                           -D BOARD_HAS_PSRAM
board_build.flash_size  =  8MB
board_build.psram_type  =  opi
lib_deps                =  lovyan03/LovyanGFX
build_src_filter        =  +<main_s3.cpp>
monitor_filters         =  esp32_exception_decoder
                           colorize